### ISSUE TITLE
JSON parsing doesn't seem to handle arrays

### ISSUE THREAD

**Issue by brianfay** [crucialfelix/API#1]
I would like to be able to pass arrays from javascript to SC, so that they could be used for things like arguments for a synth. If I use this handler:

newSynth: { arg reply, targetGroup, defName ... argsFromJs;
    var synth = Synth(defName, target:nodeDict.at(targetGroup), args: argsFromJs, addAction:'addToHead');
    nodeDict.put(synth.nodeID, synth);
    reply.value(synth.nodeID);
  }

and my request from supercolliderjs is something like this:
 var res = yield callSC('triggerfish.newSynth',[1000, "mySynth","freq", 1000, "inBus", 0, "outBus", 1]);

Then everything is fine.

But it I pass an array for some of the buffers:
 var res = yield callSC('triggerfish.newSynth',[1000, "mySynth","freq", 1000, "inBus", [0, 1], "outBus", 1]);

It breaks - sclang actually does not format the response correctly and scjs throws an exception and dies (see my pull request in supercolliderjs).
https://github.com/crucialfelix/supercolliderjs/pull/13

**Comment by brianfay** [comment]
Just realized that I'm using the old API from svn, so that could be part of the problem. I'll try again on sc 3.7

**Comment by brianfay** [comment]
Installed 3.7 and got the right version of API from git. It seems like this is actually working and I gave a false report - I need to do a little more testing to make sure it's definitely doing the right thing with the arrays, but it's not crashing the app like it was earlier!

**Comment by brianfay** [comment]
Alright, I've messed around a bit more with this, and I don't think this is a problem (the version on SVN is out of date, this version on git seems to work).

I'm enjoying a nice ping-pong delay right now, the arrays were set from javascript!

Sorry for the false issue, closing now.

**Comment by crucialfelix** [comment]
good to hear
