### ISSUE TITLE
Better support for JSON, parseYAML parses an array of numbers as arrays of strings

### ISSUE THREAD

**Issue by diegovdc** [crucialfelix/API#4]
I see that `JSON.parse` is simply a call to `.parseYAML`, however that method fails to type correctly things like an array of numbers.

i.e.
```
JSON.parse("[1,2,3]")[0].isNumber // false
```

Is there any chance of getting better support for this?

**Comment by diegovdc** [comment]
I see you actually opened an issue at the Supercollider repo, with the exact same problem (https://github.com/supercollider/supercollider/issues/1154 ). Too bad there is no solution yet.

**Comment by crucialfelix** [comment]
Yeah, it's not something that the API quark can fix.  Of course I wouldn't want to implement my own JSON parser in supercollider either.

If you can send `{"items": [1, 2, 3]}` then you will be fine I think.
